name: Build Component B

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/comp_B_actions/prepare_deps

      - name: Build Component B
        run: |
          echo "I am building component B!!!"
