name: Build Component A on PR

on:
  workflow_dispatch:

concurrency:
  # github.workflow: the workflow name is used to generate the concurrency group (e.g. Workflow 1).
  # That allows you to have more than one different workflow (eg. workflow1.yaml and workflow2.yaml) triggered on the same event (e.g. a PR).
  # Otherwise, workflow1.yaml would cancel workflow2.yaml or viceversa.
  # github.event.pull_request.number: when the trigger event is a PR, it will use the PR number (e.g. workflow1-33).
  # github.ref: when the trigger is a push, it will use the branch or tag name (e.g. workflow1-branch1).
  #if cancel-in-progress is false, when a new workflow is triggered,
  # the currently running workflow won't be cancelled, and the new workflow will be queued until the previous one is done.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_comp_A:
    uses: ./.github/workflows/compA/build.yaml
