name: Build Component A

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/comp_A_actions/prepare_deps

      - name: Build Component A
        run: |
          echo "I am building component A!!!"
