name: Matrix Job Example

on:
  workflow_call:

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        option: ['a', 'b', 'c']
    outputs:
      option_${{ matrix.option }}: ${{ steps.set_output.option_output }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo option value
        run: echo "The option is ${{ matrix.option }}"
        id: echo_step
      - name: Set output
        run: echo "option_output=${{ matrix.option }}" >> $GITHUB_OUTPUT
        id: set_output

  consume-output-job:
    runs-on: ubuntu-latest
    needs: matrix-job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print outputs from matrix job
        run: |
          echo "Matrix output: ${{ needs.matrix-job.outputs.option_output }}"
