name: Matrix Job Example

on:
  workflow_dispatch:
    inputs:
      option:
        description: |
          This is a description for the parameter
          It uses multiple lines

          and even `line` skips
        default: "a"
        required: false
        

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: ['1', '2']
        y: ['a', 'b']
    steps:
      - name: Echo option value
        run: echo "The option is ${{ matrix.option }}"
        id: echo_step


  matrix2-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: ['1', '2']
        include:
          - x: '1'
            y: 'a'
          - x: '2'
            y: 'b'
    steps:
      - name: Echo option value
        run: echo "The option is ${{ matrix.option }}"
        id: echo_step

  matrix3-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - x: '1'
            y: 'a'
          - x: '2'
            y: 'b'
    steps:
      - name: Echo option value
        run: echo "The option is ${{ matrix.option }}"
        id: echo_step
