name: Validate code in the merge queue

on:
  merge_group:
  pull_request:

jobs:
  validate-pr:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run slow CI (emulated by a long sleep)
        run: sleep 300
      - name: Fail or not
        run: |
          exit 1
        shell: bash
